- name: install and run nginx
  hosts: 172.31.20.68
  become: true
  tasks:
    - name: install nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: start nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
