- name: conditions example
  hosts: local
  connection: local
  vars:
    Is_Live: false
  tasks:
    - name: check live or not
      debug:
        msg: "yes, it is live"
      when: Is_Live
# when is_live is true it prints yes, it is live
# when is_live is false it's skips
