- name: check number is greater than 10 0r not
  hosts: local
  connection: local
  vars:
    NUMBER: 5

  tasks:
    - name: check number is greater than or not
      debug:
        msg: "number is greater than 10"
      when: "NUMBER > 10"

    - name: check number is less than or not
      debug:
        msg: "number is less than 10"
      when: "NUMBER < 10"
